name: Release

on:
  push:
    tags:
    - v*

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh release create '${{ github.ref_name }}' --title '${{ github.ref_name }}' --draft --notes-file .github/RELEASE_TEMPLATE.md
